version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "${PORT}:${PORT}"
    networks:
      - eco_network
    environment:
      - PORT=${PORT}
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
    depends_on:
      - mongodb

  client:
    build: ./client
    ports:
      - "3000:3000"
    networks:
      - eco_network
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - eco_network
    volumes:
      - mongo-data:/data/db

networks:
  eco_network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
